# Generated by Django 3.0.7 on 2022-08-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220829_2139'),
    ]

    operations = [
    ]
